de:
  contentDir: content/de
  title: Robert Walsers Biel
  languageName: Deutsch
  weight: 1
  params:
    footer: |
      © Christine Schranz
fr:
  contentDir: content/fr
  title: Bienne vue par Robert Walser
  languageName: Français
  weight: 2
  params:
    footer: |
      © Christine Schranz