baseURL: https://nfriedli.github.io/robert-walser/
title: Balade Robert Walser

canonifyURLs: true
publishDir: docs

defaultContentLanguage: fr
defaultContentLanguageInSubdir: true

languages:
  de:
    contentDir: content/de
    title: Robert Walser in Biel
    languageName: Deutsch
    weight: 1
    params:
      footer: |
        Eine Projekt von Stadt Biel / Christine Schranz
  fr:
    contentDir: content/fr
    title: Robert Walser à Bienne
    languageName: Français
    weight: 2
    params:
      footer: |
        Un projet de la ville de Bienne / Christine Schranz

disableKinds:
  - taxonomy
  - term
  - RSS
  - sitemap
  - robotsTXT
  - 404

markup:
  goldmark:
    renderer:
      unsafe: true
